services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev"]
    depends_on:
      - backend

  backend:
    build:
      context: ./go-backend
    ports:
      - "8080:8080"
    volumes:
      - ./go-backend:/app
      - /app/tmp
    command: ["air", "-c", ".air.toml"]
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=communicator_db
      - PEPPER=cw0OfDCYO6ILZ8r4FsyaEX0GhuFr9wTd1YRzjNhAqXusRprdkobaxPKSJbLt5OV6
    depends_on:
      - database

  database:
    build:
      context: ./sql-database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=communicator_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
