# .air.toml
# Config file for Air - https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = []
  include_file = []
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  log = "build-errors.log"
  poll = true
  poll_interval = 500
  delay = 1000
  stop_on_error = false
  send_interrupt = false
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
